### ISSUE TITLE
Remove useless pages

### ISSUE THREAD

**Issue by thijsvb** [richelbilderbeek/richelbilderbeek.github.io#1]
Pages like [this](http://richelbilderbeek.github.io/LonelierPong.html) instead of [this](http://richelbilderbeek.github.io/LonelierPong/LonelierPong.html)

**Comment by richelbilderbeek** [comment]
Thanks for the suggestion.

This is, however, by design: `http://richelbilderbeek.github.io/LonelierPong.html`
is copied to `http://richelbilderbeek.github.io/LonelierPong/LonelierPong.html` by the `build.sh`
script, to keep the HTML pages absent from the `LonelierPong` GitHub, but to have it in the `richelbilderbeek.github.io` GitHub instead.

I never link to the former static  HTML pages. Or did I miss something?

**Comment by richelbilderbeek** [comment]
Well, my architecture may be clumsy, but appears to be fine enough.
